### ISSUE TITLE
how to run on windows

### ISSUE THREAD

**Issue by ted423** [TeaM-TL/FotoKilof#118]
**Describe the bug**

**To Reproduce**
```
python -m pip install FotoKilof-3.8.3-py3-none-any.whl
Processing e:\downloads\fotokilof-3.8.3-py3-none-any.whl
Requirement already satisfied: tkcolorpicker in d:\dropbox\sync programs\mediatool\x264_launcher\extra\vapoursynth-64\lib\site-packages (from FotoKilof==3.8.3) (2.1.3)
Requirement already satisfied: pillow in d:\dropbox\sync programs\mediatool\x264_launcher\extra\vapoursynth-64\lib\site-packages (from FotoKilof==3.8.3) (8.3.1)
FotoKilof is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
```

the path is already add 

after run fotokilof ,no window come out ,and no keep in task manager

windows 10 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: ![image](https://user-images.githubusercontent.com/7042766/155444336-3439fa6f-d8a6-48e5-80ab-3572573d6427.png)

**Additional context**

**Comment by Asinin3** [comment]
Same issue.

**Comment by ThomasRettig** [comment]
Can confirm on Windows 11 too

**Comment by TeaM-TL** [comment]
Thank you for info. Currently I have no access to Windows 11 to check it.
As I see you forgot to install pywin32, it os neccessary under Windows, try
python -m pip install pywin32 fotokilof

**Comment by Hyiker** [comment]
I encountered the same problem. By debugging the source code, I figured it out that this problem is probably due to non-utf8 system encoding instead of Windows 11.
The error log was like:
```
C:\Users\xxx\AppData\Local\Temp\fotokilof_carbene_fonts_list
Traceback (most recent call last):
  File "C:\Users\xxx\Projects\FotoKilof\src\fotokilof.py", line 2381, in <module>
    img_text_font_dict = fonts()    # Reading available fonts
  File "C:\Users\xxx\Projects\FotoKilof\src\fotokilof.py", line 610, in fonts
    result = magick.get_fonts_dict(GM_or_IM)
  File "C:\Users\xxx\Projects\FotoKilof\src\magick.py", line 163, in get_fonts_dict
    for line in file:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 6025: illegal multibyte sequence
```
And it can be solved simply by specifying the encoding utf-8(src/magick.src, line 148):
```python
file = open(file_font, "r", encoding="utf-8")
```

**Comment by TeaM-TL** [comment]
fixed in 3.8.5

**Comment by niceslimenotbad** [comment]
bug repeats again. fotokilof command does not open a window in windows 11

**Comment by TeaM-TL** [comment]
did you use\:
 python -m pip install pywin32 fotokilof

pywin32 has to be installed

**Comment by TeaM-TL** [comment]
try latest version 4.0.0
install:
python -m pip install pywin32 wand fotokilof
during install ImageMagick, enable libraries! and add to path
