### ISSUE TITLE
Where is the Windows binary?

### ISSUE THREAD

**Issue by lexterror** [TeaM-TL/FotoKilof#121]
I cant find the Windows binary!

**Comment by TeaM-TL** [comment]
Install via pypi as described in readme:
-  install fresh ImageMagick (remember to add path into %PATH% environment variable during installation)
- fresh Python3 (remember to add path into %PATH% environment variable during installation)
- install from PyPi by: python -m pip install pywin32 fotokilof

I do not plan to provide binaries for Windows. If you have time to prepare binaries and installer eg. NSIS, do it!
