### ISSUE TITLE
Can‘t find the 3.7.7 FotoKilof-windows-gui version

### ISSUE THREAD

**Issue by scillidan** [TeaM-TL/FotoKilof#122]
Great projects.
Can exercise on it, very useful for using the imagemagick to generate pictures.
But I only find the `windows-gui` version `3.3.0` on https://github.com/ruisaraiva19/favycon/releases

**Comment by TeaM-TL** [comment]
Install via pypi as described in readme:

    install fresh ImageMagick (remember to add path into %PATH% environment variable during installation)
    fresh Python3 (remember to add path into %PATH% environment variable during installation)
    install from PyPi by: python -m pip install pywin32 fotokilof

I do not plan to provide binaries for Windows. If you have time to prepare binaries and installer eg. NSIS, do it!

**Comment by scillidan** [comment]
Thanks for guide :)
