### ISSUE TITLE
.webm selection in Windows File Explorer

### ISSUE THREAD

**Issue by ifeelagood** [TeaM-TL/FotoKilof#124]
**Is your feature request related to a problem? Please describe.**
When selecting a webm file on windows, you must first select "all files". .webm is not recognised as a image media file.

**Describe the solution you'd like**
Add .webm to the supported media files

**Describe alternatives you've considered**
It does not really matter, but i thought I'd open an issue anyways as it seems like it would be a quick fix

**Additional context**
Windows 10 21H2

**Comment by TeaM-TL** [comment]
.webm is format video, FotoKilof is dedicated for pictures.
ImageMagick support more than 200 formats, it would be useless to add every supported format into list
