### ISSUE TITLE
MacOS:  ImageMagick or Wand-py not found

### ISSUE THREAD

**Issue by gasparschott** [TeaM-TL/FotoKilof#151]
imagemagick (and graphicsmagick) installed with homebrew
pyenv versions: 3.11.1 3.10.1 3.9.9 3.8.12 3.7.13 system
MAGICK_HOME set in .zshrc

FotoKilof launches with alert: 
"ImageMagick nor GraphicsMagick are not installed in you system. Is impossible to process any graphics."
All "Image" buttons ("File Selection, Clipboard, etc.) in the UI are unresponsive, so no file can be opened or processed.

Running MacOS 13.2 on a 16in 2021 M1 Pro MacBookPro.

**Comment by TeaM-TL** [comment]
Hi, I tested on Montery and Catalina, and it works.
Probably path MAGICK_HOME is wrog.MAGICK_HOME is neccessary if youinstan ImageMagic by brew ad python by macports or dmg package.
Try install python and image magick by brew:
brew install imagemagick python@3.11 python-tk@3.11
and do't set MAGICK_HOME

**Comment by gasparschott** [comment]
Thanks, I did all this and still receive the same errors. What else can I try?

**Comment by TeaM-TL** [comment]
GraphicsMagick is not neccesary, If you don't need it - remove it. 
Next try:
brew upgrade
What is in your PATH?
How you install python? by brew or macports or by dmg or native?

**Comment by TeaM-TL** [comment]
no problem no issue ;-)
If you will encounter problem with starting FotoKilof, do not hesitate to reopen this topic
