### ISSUE TITLE
Windows: Having problems installing program

### ISSUE THREAD

**Issue by autisticgamer-500** [TeaM-TL/FotoKilof#152]
I am having a lot of trouble setting up/installing the program. I have tried both the .whl package and the source code. The instructions are unclear as to what to do.
When i enter `python -m pip install pywin32 fotokilof` into the command prompt, it tells me that Python could not be found, even though I have Python 3.9 on my computer, just not under the program files folder.

**Comment by TeaM-TL** [comment]
Hi
I think you don't have python in Path environment variable.
Type in terminal: echo %Path%
and check if you have python there.If not, you have to add by Control Panel or reinstall Python (but durig reinstall mark checkbox - add to Path)

**Comment by TeaM-TL** [comment]
no answer = no problem

**Comment by autisticgamer-500** [comment]
Do I do this after regularly opening python?

**Comment by autisticgamer-500** [comment]
Also sorry for the late reply, I get a lot of emails and my phone doesn’t
always inform me

**Comment by TeaM-TL** [comment]
run cmd
type: echo %Path%
what is answer?
