### ISSUE TITLE
Compose (merge) two images

### ISSUE THREAD

**Issue by Nurovek** [TeaM-TL/FotoKilof#159]
**As a user, I'd like to have a GUI way of combining two images.**
The imagick command to use is:
```magick imageA.jpg imageB.jpg -gravity center -background white +append -quality 100 imageA-imageB.jpg```

**Describe the solution you'd like**
- The user checks the "Compose" box (which may be in the "Tools" frame)
- The user is then prompted to choose Image A, and Image B in the "Original" Frame.
- The output image is previewed in the "Result" frame
- The user can choose the output quality (defaults to 100)
- The user can choose the background color (default to white)
- The user can choose to append horizontally (adds ```+append``` param) or vertically (adds ```-append``` param)
- The user can toggle the resizing if the two images aren't the same size (defaults to false, when true, adds ```-set option:ww "%[fx:min(u.w,v.w)]" -set option:hh "%[fx:min(u.h,v.h)]" -resize "%[ww]x%[hh]"``` to the command)
- The user can rename the output file (defaults to combination of the two file names with a dash)
- The user can choose the "gravity" (junction between the two images), defaults to center (doc of gravity here https://www.imagemagick.org/script/command-line-options.php#gravity)

**Describe alternatives you've considered**
The alternative is to use the command in my CLI which is frustrating and can be a hassle

**Comment by TeaM-TL** [comment]
Hi Kevin.
may thanks, good idea, I was thinking about it but still thinking.
You did great job by describing how it should works.
Let me a while, This month is busy. In September I will have more time for it

**Comment by Nurovek** [comment]
Hi, you are welcome, and no problem, take your time 🙂
I may have forgotten some use cases & params in the issue (my use case of the image combining is for creating manga double-paged spreads)

If so, I'll add some either by editing the OG message or adding a new comment 🙂

**Comment by TeaM-TL** [comment]
fixed in 4.4.0

![Image](https://github.com/TeaM-TL/FotoKilof/assets/55061453/967a52eb-27f9-4a49-a6a4-fe09acca467f)
