### ISSUE TITLE
dist - linux packages

### ISSUE THREAD

**Issue by TeaM-TL** [TeaM-TL/FotoKilof#16]
- [ ] - Slackware - tgz
- [ ] - Ubuntu - deb
- [ ] - OpenSUSE - rpm
- [ ] - CentOS - rpm
- [ ] - Arch/Aurox/Manjaro - aur

**Comment by arun54321** [comment]
Please make arch aur package.

**Comment by TeaM-TL** [comment]
I don't know how to do ii. Give me instructions

**Comment by bastidest** [comment]
I added an [Arch package](https://aur.archlinux.org/packages/fotokilof/) in the AUR. It includes a desktop file for launching it. Any feedback is appreciated.

Currently I need to patch the `setup.py` and `__init__.py` file. Maybe this change should be integrated upstream (here):
```diff
diff --git a/setup.py b/setup.py
index cae2607..dd64af6 100644
--- a/setup.py
+++ b/setup.py
@@ -22,5 +22,10 @@ setuptools.setup(
         "Operating System :: OS Independent",
     ],
     python_requires='>=3.6',
-    install_requires=['configparser','tkcolorpicker']
+    install_requires=['configparser','tkcolorpicker'],
+    entry_points = {
+        "gui_scripts": [
+            "fotokilof = src.__main__",
+        ]
+    },
 )
diff --git a/src/__init__.py b/src/__init__.py
new file mode 100644
index 0000000..8522b45
--- /dev/null
+++ b/src/__init__.py
@@ -0,0 +1,3 @@
+import sys
+import os.path
+sys.path.insert(1, os.path.dirname(__file__))
```

I can create a PR for that, if you think it's useful.

**Comment by TeaM-TL** [comment]
Thanks! I'm goint to check your idea and merge your changes

**Comment by TeaM-TL** [comment]
I think, that distribution via PyPi by me is enough. If somebody would like to make packages - feel free.
