### ISSUE TITLE
fotokilof does not run on Linux Mint 21.2

### ISSUE THREAD

**Issue by bianchifan** [TeaM-TL/FotoKilof#160]
System:
![Bildschirmfoto vom 2023-08-26 17-06-42](https://github.com/TeaM-TL/FotoKilof/assets/17491743/d411e8a7-fc05-476f-aa5a-4a0d58121905)

Terminal:
![Bildschirmfoto vom 2023-08-26 17-09-31](https://github.com/TeaM-TL/FotoKilof/assets/17491743/e60c437c-042f-4dee-9228-cfdc99f6cb12)

**Comment by TeaM-TL** [comment]
please install python3-tk

**Comment by bianchifan** [comment]
python3-tk version 3.10.8-1 is installed

**Comment by TeaM-TL** [comment]
try to reinstall PIL
pip install --upgrade pil

**Comment by bianchifan** [comment]
THX!
That did the trick!
Updated pillow from 9.0.1 to 10.0.0
