### ISSUE TITLE
No Instructions for MacOS installation or building.

### ISSUE THREAD

**Issue by Danrancan** [TeaM-TL/FotoKilof#166]
There really aren't any instructions on how to install this and keep it updated on MacOS. I am running MacOS Monterey and want to know how I can get this application running, as well as check for updates on boot. Please help?

**Comment by TeaM-TL** [comment]
Try:
brew install imagemagick python@3.11 python-tk@3.11
python3 -m pip install --upgrade fotokilof
python3 -m fotokilof

**Comment by TeaM-TL** [comment]
Readme updated, thanks
