### ISSUE TITLE
It would be great to have software made for non-uber-nerds, i.e., a simple exe file to install

### ISSUE THREAD

**Issue by kngfbng** [TeaM-TL/FotoKilof#168]
I open Github following a Google link after a Reddit recommendation and there's s million different things that make no sense at all to me. I look for a download link and there's no such thing, only links to Python and ImageMagick. So I install both and now I need an installer for FotoKilof? I'd expect to, but there, again, is nothing. But there's some obscure command line below the links in the Windows install section with no explanation whatsoever, so maybe I should type that in the command prompt? I try that, Windows has no idea of what I'm talking about. Conjuring all the nerdness I can muster, I suspect python folks like to use py and I try that, so Windows regurgitates a bunch of lines that also make no sense to me, but it seems to be progressing the.. install? By that point, I'm not really sure, I'm just throwing stuff at the wall to see it I get stuck. And I do, because the routine is done and there's no FotoKilof to be found on my PC. Start menu? Nothing. Desktop? Nothing. Full-disk search for "fotokilof"? _Nothing._ (n.e.: Windows found two folders in AppData -- which I'm just nerd enough to know exists, but not to know what exactly it does -- for FotoKilof, one dist-info with fully useless files and another with a bunch of .py files, which I assume are from Paraguay. There's a gui.py, which I hoped would, you know?, open the GUI I was promised, but nope, it just pops up a command prompt window and closes it without displaying anything. To me, a non-uber-nerd, that's as good as a kick to the balls.)

So how the coitus am I supposed to launch it?? I'm 100% sure that uber-nerds reading this are appalled that I don't know such basic stuff as installing a pythong script feature recursive non-binding binary cornmeal authorizer or whatever it is, and to them I say stuff it. I'm so tired of finding niche software on Github that go nowhere because I'm completely clueless as to what to do with the files and then there's zero instructions on the page -- or, when there is, it's obscure enough that you need a master's in computer science to follow with all the lingo and background knowledge required.

Is it that hard to make an installer? I could be mistaken, seen as I'm not an uber-nerd, but isn't it a matter of picking up an established installer maker, selecting files and setting a few parameters? So what if they're not open source -- isn't there any open source installer maker?; someone should publish one in an unintelligible page that only other uber-nerds will understand.

Download install.exe. Execute it. Click next a few times. ????. Profit.

When did simplicity go out of fashion? When did we start needing to know enough to be able to program the damn thing ourselves only to install software?

The way it is, Github seems to me like a huge circle jerk where one developer makes cutesy software that other developers on Github will be able to run and that's it. Kind of like how academic knowledge is often a means and an end in and of itself, with researchers publishing mastubatory papers that will matter exclusively to other masturbating researchers and never leave academia to reach the general public. Perhaps making things accessible to normies would ruin the fun at the programmers' club? If anyone can run it, how will uber-nerds feel superior for knowing how to take twenty-eight times as long to do the same thing as double clicking?

I just want a freaking installer.

**Comment by TeaM-TL** [comment]
Hi kngfbng

I had an idea to prepare [windows installer](https://github.com/users/TeaM-TL/projects/2?pane=issue&itemId=26928841).
Early version of FotoKilof had windows executables but without installer, to work you had to install ImageMagick. But performance was very poor.
Now Fofokilof use ImageMagick via Wand library, efects: performance on Windows system is almost as on Linux/macOS, less annoying black window etc.
FotoKilof works properly and install way is acceptable for me, but may be not obvious for everybody. Because I have really reduced access to Windows, low motivation for make installer (even I have some experiences from the past) and not enough time for it - I have no plan to do it.
If you have time, try, many people will be grateful, me too.
Good guys prepared packages for FreeBSD, Slackware or other Linux systems, prepared translation to many languages, gave suggestion how to improve somethings.
If you have time and motivation, do it! It is not rocket science. Stop complain, start work!

Regards
Tomek

**Comment by Melodycloudu** [comment]
As a reponse to this can we at least get a pretty direct and easy to follow installation instruction for windows? (and other os'es too)

**Comment by TeaM-TL** [comment]
Instruction how to install there is in README, always visible as first page. After copy and paste:
Download and install requirements:
-    [Python3](https://www.python.org/) - add path into %PATH% environment variable,
-    [ImageMagick](https://imagemagick.org/script/download.php#windows) - add path into %PATH% environment variable, enable install libraries!

Run in terminal window:
python -m pip install pywin32 fotokilof

**Comment by TeaM-TL** [comment]
executable fotokilof should be available to use in 4.4.3

**Comment by kngfbng** [comment]
> executable fotokilof should be available to use in 4.4.3

Thanks for understanding.

I don't mind learning even if it takes some effort at first, but the lack of a readily accessible way for regular people to run the software will just keep regular people from running the software. When I'm two hours into looking for help with a task and find what appears to be the perfect solution only to find out I need to learn a whole new branch of computing that, despite powerful, is convoluted, it's frustrating. Especially after I spend another hour going in circles and have to just give up and try whatever is on the seventh page of Softonic -- which won't work, but I'll know that in minutes because I had an installer.

Meh, ignore the rant(s). Rock on.
