### ISSUE TITLE
Windows python 3.1 ImageMagick or Wand-py not found 

### ISSUE THREAD

**Issue by PippoApps** [TeaM-TL/FotoKilof#170]
Just installed with pip, and on Launch, I get ImageMagick or Wand-py not found on 3 rows.
ImageMagick is installed and works fine.

**Comment by TeaM-TL** [comment]
Hi
Did you during installation of ImageMagick - add path into %PATH% environment variable, enable install libraries! tick two checkbokx?
please check in terminal (cmd.exe): echo %Path% - in path should be ImageMagick
later you should run in terminal (cmd.exe)
python -m pip install pywin32 fotokilof

**Comment by PippoApps** [comment]
Thank you. It works very well after reinstalling IM.
I would like to use this in order to test IM commands. Is there a way to see the real text commands going on behind the scenes?

**Comment by TeaM-TL** [comment]
> Is there a way to see the real text commands going on behind the scenes?
Yes, find and watch .fotokilof.log
