### ISSUE TITLE
[Suggestion] Add a note in README that only Python>=3.9 is supported

### ISSUE THREAD

**Issue by abceleung** [TeaM-TL/FotoKilof#171]
**Is your feature request related to a problem? Please describe.**
I can't launch fotokilof with Python 3.7 because in `__main__.py`, the argument `encoding='utf-8'` in `logging.basicConfig` (line 73) is only valid with Python >= 3.9. I can launch fotokilof after manually commenting the `encoding` argument.

**Describe the solution you'd like**
Add a note in README that only Python>=3.9 is supported.

**Describe alternatives you've considered**
Upgrade my Python, I guess

**Comment by TeaM-TL** [comment]
fixed
