### ISSUE TITLE
Multiple File Processing?

### ISSUE THREAD

**Issue by maxkaplan** [TeaM-TL/FotoKilof#178]
Apologies in advance if this has already been discussed, but I could not find any mention of it in previous issues.

Is there any plan to allow users to select multiple image files (or an entire directory) for batch processing?

I understand if this isn't the objective of the software; but it would save me (and possibly others) from having to write commands like this:

```
Get-ChildItem *.jfif | ForEach-Object {
    $output = $_.BaseName + ".jpg"
    magick $_.FullName -quality 100 $output
}

Get-ChildItem *.webp| ForEach-Object {
    $output = $_.BaseName + ".jpg"
    magick $_.FullName -quality 100 $output
}
```

Best,

**Comment by TeaM-TL** [comment]
there is option to process one file or whole directory:

**Comment by maxkaplan** [comment]
Ok great thanks.
