### ISSUE TITLE
conversion - order selection

### ISSUE THREAD

**Issue by TeaM-TL** [TeaM-TL/FotoKilof#2]
possibility to choose what should be processed as a first, second and third

**Comment by TeaM-TL** [comment]
Since custom command we are able to compose own scenario for processing

**Comment by gingerbeardman** [comment]
I was just about to file this.

It would be hard work, but I think it would be best to be able to reorder things by drag and drop options panels? Alternatively, up/down arrows on each options panel to change their position in the order.

Editing command line is good workaround, but if I change the order and then change the options and press apply then the command line contents no longer make sense, in that they no longer reflect the selected options, sometimes with double options with different meaning.

eg. 

1. select scale
2. select black & white
3. select custom
4. change order of command line
5. click execute
= repeated elements on command line
