### ISSUE TITLE
Use setuptools instead of PyInstaller.

### ISSUE THREAD

**Issue by tnilzon** [TeaM-TL/FotoKilof#59]
I made a "Package request" to add `FotoKilof` to the Manjaro repository. Please see this forum post: <https://forum.manjaro.org/t/gui-front-end-for-imagemagick-request-add-this-to-the-repo/119499/5?u=tnilzon>

**Comment by TeaM-TL** [comment]
Thank you!
I will try to use setuptools

**Comment by tnilzon** [comment]
> Thank you!
> I will try to use setuptools

Sounds great, thanks!

**Comment by TeaM-TL** [comment]
Done. FotoKilof is avalable via pip install fotokilof from pypi

**Comment by tnilzon** [comment]
> Done. FotoKilof is avalable via pip install fotokilof from pypi

Great, thanks!

**Comment by TeaM-TL** [comment]
try it, I hope it's correct

**Comment by TeaM-TL** [comment]
It works, but:
pip install fotokilof - will install dependencies and fotokilof
but for run
pip download fotokilof
python FotoKilof-3.2.1-py3-none-any.whl/src
but there are no locales.

In next days I will have time to prepare valid setup.py
