### ISSUE TITLE
No module named 'touch'

### ISSUE THREAD

**Issue by yochananmarqos** [TeaM-TL/FotoKilof#60]
**Describe the bug**

```
Traceback (most recent call last):
  File "fotokilof.py", line 31, in <module>
  File "/usr/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "common.py", line 16, in <module>
  File "/usr/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "magick.py", line 23, in <module>
ModuleNotFoundError: No module named 'touch'
[16244] Failed to execute script fotokilof
```

I installed [`touch`](https://pypi.org/project/touch), but receive the same error.

**To Reproduce**
1. Install via my [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/tree/master/fotokilof) on Arch Linux / Arch-based distro
2. See error

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Desktop:  GNOME 3.34.3

**Additional context**
It would be great to have the dependencies listed in the `README`.

**Comment by TeaM-TL** [comment]
You are right. This probem appear only with Python 3.8, for 3.7 not
In fact touch was not neccessary and has been disabled.
Update your sandbox andtry again!

**Comment by yochananmarqos** [comment]
I tried building from master and it failed:

```
= Locale =========================
bg
fotokilof.mo  fotokilof.po
de
fotokilof.mo  fotokilof.po
id
fotokilof.mo  fotokilof.po
pl
fotokilof.mo  fotokilof.po
= PyInstaller ====================
UPX:  --noupx
ONEFILE: 
= Remove working directories ====================
36 INFO: PyInstaller: 3.6
36 INFO: Python: 3.8.1
37 INFO: Platform: Linux-5.5.2-1-MANJARO-x86_64-with-glibc2.2.5
37 INFO: wrote /home/yochanan/Documents/pkgbuilds/fotokilof-git/src/fotokilof/fotokilof.spec
41 INFO: UPX is available.
42 INFO: Removing temporary files and cleaning cache in /home/yochanan/.cache/pyinstaller
Traceback (most recent call last):
  File "/usr/sbin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.6', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3.8/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3.8/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "/home/yochanan/Documents/pkgbuilds/fotokilof-git/src/fotokilof/fotokilof.spec", line 6, in <module>
    a = Analysis(['src/fotokilof.py'],
  File "/usr/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 191, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script '/home/yochanan/Documents/pkgbuilds/fotokilof-git/src/fotokilof/src/fotokilof.py' not found
= Packing ====================
= Something went wrong... ====================
```

**Comment by TeaM-TL** [comment]
I renamed fotokilof.py to __main__.py, and I forgot to update a script.
I'mworking for it

**Comment by yochananmarqos** [comment]
It builds now, but I did see this UPX error:

```
38 INFO: An exception occured when testing for UPX:
38 INFO:   ValueError("invalid literal for int() with base 10: '96-git-d7ba31cab8ce'")
38 INFO: UPX is not available.
```

It won't run, though. I tried installing `convert` and `convert2` with the same result:

```
Traceback (most recent call last):
  File "src/fotokilof.py", line 31, in <module>
ModuleNotFoundError: No module named 'convert'
[31427] Failed to execute script fotokilof
```

**Comment by TeaM-TL** [comment]
convert is a module of fotokilof.
I have encountered problem with pyinstaller too, under Ubuntu and Manjaro, but different.
I'm working on solution

**Comment by TeaM-TL** [comment]
remove __init__.py and pyinstaller will work again

**Comment by TeaM-TL** [comment]
done, try it

**Comment by yochananmarqos** [comment]
No difference using `install.sh` or `Manjaro-KDE-18.1.5.sh`.

**Comment by TeaM-TL** [comment]
For setuptools is script: `0_pypi_setuptools.sh` and for run: `1_pypi_run.sh`
Here https://github.com/TeaM-TL/FotoKilof/tree/3.2.2 is package for Manjaro - made on my Manjaro via `Manjaro-KDE-18.1.5.sh`

**Comment by yochananmarqos** [comment]
I'm confused. I should be able to just run `python setup.py install`, but it doesn't install the files properly. Running `0_pypi_setuptools.sh` just creates the PyPI tarball & wheel package. `Manjaro-KDE-18.1.5.sh` just runs `install.sh`. How did you install it on Manjaro? Doesn't sound like you used Pacman.

**Comment by TeaM-TL** [comment]
'Manjaro-KDE-18.1.5.sh` create only package. Unpack it eg to `/opt` and run `/opt//fotokilof/fotokilof`.
I have problem with wheel package. is possible to install `python3 -m pip install fotokilof`, but I cannot run instaled package. I can run only wheel, eg via script `1_pypi_run.sh`.
Do you have and idea how to prepare setup.py and source properly?

**Comment by yochananmarqos** [comment]
Now we're just going in circles. I've been using the `install.sh` the whole time.

I really don't know much about coding, only writing PKGBUILDs.

**Comment by yochananmarqos** [comment]
with 3.3.2, it's building now with my above PKGBUILD.

**Comment by TeaM-TL** [comment]
It means ok? it works?

**Comment by yochananmarqos** [comment]
Yes, it works with the `install.sh`.

**Comment by TeaM-TL** [comment]
good job! will you prepare package for Manjaro?

**Comment by yochananmarqos** [comment]
I technically already prepared it, that's what the PKGBUILD is. However, I'm not part of the Manjaro team so I can't add it to the community repo. I've shared my PKGBUILD on the [package request thread](https://forum.manjaro.org/t/gui-front-end-for-imagemagick-request-add-this-to-the-repo/119499/11) on the Manjaro forum. If enough people want it, maybe I'll add it to the AUR (Arch User Repository).

**Comment by TeaM-TL** [comment]
ok. thank you. Happy using FotoKilof
