### ISSUE TITLE
How to run on macOS?

### ISSUE THREAD

**Issue by borekb** [TeaM-TL/FotoKilof#68]
The releases don't contain DMG or similar so I followed [this section of README](https://github.com/TeaM-TL/FotoKilof/blob/ee7b84ebcb2c0557075fb04b369e8cf398739a6b/README.md#as-pypi-package):

```
$ pip3 install fotokilof
Collecting fotokilof
  Downloading FotoKilof-3.4.0-py3-none-any.whl (35 kB)
Collecting configparser
  Downloading configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Collecting tkcolorpicker
  Downloading tkcolorpicker-2.1.3-py3-none-any.whl (31 kB)
Collecting Pillow
  Downloading Pillow-7.0.0-cp37-cp37m-macosx_10_6_intel.whl (3.9 MB)
     |████████████████████████████████| 3.9 MB 1.1 MB/s
Installing collected packages: configparser, Pillow, tkcolorpicker, fotokilof
Successfully installed Pillow-7.0.0 configparser-4.0.2 fotokilof-3.4.0 tkcolorpicker-2.1.3
```

What do I do next? I tried this:

```
$ pip show fotokilof
Name: FotoKilof
Version: 3.4.0
Summary: Nice gui for ImageMagick
Home-page: https://github.com/TeaM-TL/FotoKilof
Author: Tomasz Łuczak
Author-email: tlu@team-tl.pl
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires: configparser, tkcolorpicker
Required-by:
```

This is the contents of the site-packages folder:

![Screenshot 2020-03-17 at 11 20 48](https://user-images.githubusercontent.com/101152/76846817-667f4080-6841-11ea-94f2-35fbd0a402b0.png)

Is it expected to have just "src" in there? I'd expect the folder name to be called "FotoKilof" or similar.

But it's true that running `cd site-packages && python3 src` indeed launches the app, with some warnings:

```
$ python3 src
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
2020-03-17 11:20:05.221 Python[19444:82984] CoreText note: Client requested name ".SFNSMono-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-17 11:20:05.221 Python[19444:82984] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
2020-03-17 11:20:05.248 Python[19444:82984] CoreText note: Client requested name ".SF NS Mono", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
```

<img width="1529" alt="Screenshot 2020-03-17 at 11 22 28" src="https://user-images.githubusercontent.com/101152/76846944-99c1cf80-6841-11ea-9886-e033e1db77d3.png">

Am I doing this right?

**Comment by TeaM-TL** [comment]
The shortest way to run is:
```
python3 -m pip install FotoKilof
python3 -m pip download FotoKilof
python3 FotoKilof-3.4.0-py3-none-any.whl/src
```
first install dependencies, later download wheel package and run

I know that wheel package available via pip is not perfect. 
If you have idea how to prepare package properly, don't hesitate to let me know.
I'd like to know how to prepare package for easier way to run

**Comment by borekb** [comment]
Ah, `pip download`! The README only mentions `pip install` so I was confused about where the `.whl` file should be 😄.

Unfortunately, I'm not a Python developer so I can't help here. But thanks for the info.

**Comment by TeaM-TL** [comment]
happy using FotoKilof!
I will update documentation

**Comment by TeaM-TL** [comment]
Since 3.5.2 is enough to install and run:
```
python3 -m pip install fotokilof
fotokilof
```

**Comment by 0lm** [comment]
somehow i cant start it. since the newest version 3.5.4 has no windows zip file, i installed it in my python 3.9 (on windows 10 OS). it successfully installed fotokilof in the lib site-packages folder. but there is no src in the fotokilof dist folder. (the src is a seperate folder in my case, not inside fotokilof dist, but inside site-packages folder).
next thing i do is to execute the command "python3 fotokilof" but nothing opens. (i have some experience with python. but im kinda stuck on how to start this one on my windows system)

**Comment by TeaM-TL** [comment]
Hi 0lm
I tried on Windows:
python -m pip install --upgrade fotokilof
fotokilof
it is enough to run if ImageMagick is installed and is in %Path%

**Comment by TeaM-TL** [comment]
there are no zip file, because a lot of false positive from windows antivirus

**Comment by 0lm** [comment]
> 
> 
> Hi 0lm
> I tried on Windows:
> python -m pip install --upgrade fotokilof
> fotokilof
> it is enough to run if ImageMagick is installed and is in %Path%

Unfortunately it is not working for me. i have imagemagick 7.0.11 hdri q16 dll 64bit installed, and it is in path of my sytsem variables. does matter what i write, the GUI does not open. what i tried so far (using python 3.9 64bit btw):
`python3 fotokilof`

**Comment by TeaM-TL** [comment]
Hi 0lm
let me some time, I will check it on windows machine from my friends soon

**Comment by 0lm** [comment]
Thank you. Did you have any chances to test it out on a Windows Machine by now? I still cant run it, unfortunately.

**Comment by TeaM-TL** [comment]
Hi 0lm,
I've checked and somethings is wrong with 3.5.7. I'm going to investigate it asap

**Comment by ozio** [comment]
I tried on Mac, but got this:
```
$ fotokilof
Traceback (most recent call last):
  File "/usr/local/bin/fotokilof", line 5, in <module>
    from src import __main__
  File "/usr/local/lib/python3.9/site-packages/src/__main__.py", line 39, in <module>
    from tkinter import Tk, ttk, Label, PhotoImage, PanedWindow
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```
`brew install python-tk` fixed it.

**Comment by FixitmanArizona** [comment]
Nightmare to install, having to do all this Python stuff and something called PIP which is also a nightmare to try to figure out how to install, takes hours to even figure out, and then I finally get it installed... so it says.. and there is no way to open it, either in the menu or on the desktop, or even in terminal (fotokilof: command not found and similar errors) No right click option on a picture in file manager either. What good is it if you can't open it? I think I will just stick with the original ImageMagick horrible menus that never worked all that well but at least are THERE.
Is there a way to possibly put this in the menus or at least put them in a package (a real package, not having anything to do with python, but say a .deb) and then have a menu item and/or context item to open. And drop the python crap, it doesn't work.

**Comment by FixitmanArizona** [comment]
Ok I think it's installed, but there is no way to open it. 
Xubuntu 20.04 
It was bad enough having to type stuff in a terminal just to install some python thing pip and then it supposedly installs this fotokilof thing, which apparently does nothing, no menu item, no right click context entry, won't open in terminal as you would expect running an executable. Apparently it installs files but does nothing. As bad as the menus are in Imagemagick, at least they are there and usable. 
Running it in terminal does nothing.
 fotokilof
fotokilof: command not found

OK I found the manual says type in terminal
`python3 fotokilof.py
>
All that does is make that arrow thing appear. Nothing happens after that, you can't even exit the terminal with "exit." You have to close it with the X.
A little help here? How do you just open it and use it, say with a menu item instead of mucking about in terminal in the first place? And without using this "python" programming language that apparently does nothing.

**Comment by TeaM-TL** [comment]
try to download https://github.com/TeaM-TL/FotoKilof/releases/download/3.5.9/FotoKilof-3.5.9-py3-none-any.whl
and run:
python3 ./FotoKilof-3.5.9-py3-none-any.whl/src
If you have installed python3-tk, python3-pil, imagemagick packages Fotokilof will runs

**Comment by TeaM-TL** [comment]
Better way is to install 
apt-get install python3-tk python3-pil python3-pip imagemagick
python3 -m pip install fotokilof
FotoKilof will be installed in ~/.local/bin
and run: fotokilof
or ~/.local/bin/fotokilof

**Comment by FixitmanArizona** [comment]
Ok thanks

**Comment by 0lm** [comment]
Any news about making this work on Windows? Still not working with newest version.

**Comment by TeaM-TL** [comment]
It works, I use it on Windows 10, the best way is to install:
- fresh ImageMagick (remember to add path into %PATH% environment variable during installation)
- fresh Python3 (remember to add path into %PATH% environment variable during installation)
- install from PyPi:
`python -m pip install --upgrade fotokilof`
- open cmd and type: `fotokilof`

**Comment by 0lm** [comment]
I exactly did that. Somehow still not working, it never opens a GUI.

**Comment by TeaM-TL** [comment]
Hi 0lm, you are right, I have pywin32 installed, but I don't remember when and why it was installed.
I will add info about it

**Comment by 0lm** [comment]
> 
> 
> Hi 0lm, you are right, I have pywin32 installed, but I don't remember when and why it was installed.
> I will add info about it

I assume it got installed when you were working on the GUI. Since the error logs I got talk about gui.exe not able to start. Seems like pywin32 has some things, which are used to ru the GUI properly.

**Comment by izharskiy** [comment]
>  apt-get install python3-tk python3-pil python3-pip imagemagick

helped me with 
```
Traceback (most recent call last):
  File "/usr/local/bin/fotokilof", line 5, in <module>
    from src import __main__
  File "/home/i/.local/lib/python3.9/site-packages/src/__main__.py", line 30, in <module>
    from tkinter import Tk, ttk, Label, PhotoImage, PanedWindow
ModuleNotFoundError: No module named 'tkinter'
```
on `Ubuntu 21.10 Impish Indri 5.13.0-21-generic`

please add requirements to script or to manual

**Comment by TeaM-TL** [comment]
thanks, I will add requirement for tkinter
