### ISSUE TITLE
Release macOS .app package

### ISSUE THREAD

**Issue by GalacticLion7** [TeaM-TL/FotoKilof#71]
I think it's unintuitive that you have to use the command line to launch an app. Could you release a macOS `.app` package?

**Comment by TeaM-TL** [comment]
You are right. Can you help me? I don't know how to do it and currently I have no time to learn how to prepare .app package

**Comment by GalacticLion7** [comment]
Looks a PyPi package for that:
https://py2app.readthedocs.io/en/latest/
https://pypi.org/project/py2app/
https://github.com/ronaldoussoren/py2app

**Comment by gingerbeardman** [comment]
Would love to see this, thanks.

**Comment by TeaM-TL** [comment]
As #16 Linux packages. Distribution vy PyPi is enough. If you would like to do it - feel free
