### ISSUE TITLE
Unnecessary dependency on configparser PyPI package

### ISSUE THREAD

**Issue by djmattyg007** [TeaM-TL/FotoKilof#77]
The dependency on the configparser PyPI package is unnecessary, because the minimum supported version of python is 3.6. It would be nice to have this dependency removed, as it is redundant.

**Comment by TeaM-TL** [comment]
you are right.
In fact FotoKilof doesn't need any extra packages. tkcolorpicker is optional and was removed too

**Comment by TeaM-TL** [comment]
done
