### ISSUE TITLE
Reduce width of main window to support narrow screens

### ISSUE THREAD

**Issue by gingerbeardman** [TeaM-TL/FotoKilof#79]
**Is your feature request related to a problem? Please describe.**

- The main window is very wide, approx 1600 pixels, which is too wide for my display.

**Describe the solution you'd like**

- I'd like to see support for screens that are narrower than the current main window.

  - Perhaps the input and output image could be a toggle?
  - Or the input and output could be positioned stacked vertically?
  - Just some ideas.

**Describe alternatives you've considered**

- Resize input image column to hide it so I can see all of image output column.

**Additional context**

- I use a portrait display, 1080 pixels wide, though I understand this may be an extreme case.

**Comment by TeaM-TL** [comment]
Panels are paned, you can resize every panel. You can use smaller preview eg.300px and use preview to watch picture on whole screen
![Screenshot_20210206_131359](https://user-images.githubusercontent.com/55061453/107117840-515a3880-687d-11eb-8ce1-2cb811f7c009.png)

**Comment by gingerbeardman** [comment]
It's disappointing that feel this isn't a problem and have closed this issue.

Resizing panes and obscure important content isn't really a solution to the problem. It's a more of a temporary workaround. 

Even with 300px preview I cannot make everything fit in a comfortable or usable way.

<img width="1080" alt="Screen shot 2021-02-06 at 13 49 20" src="https://user-images.githubusercontent.com/49612/107119856-26261800-6882-11eb-9f34-692a7357d4c8.png">

**Comment by TeaM-TL** [comment]
Ok, you are right,it is real problem with screen width. I have idea:
Two set of tabs:
First tab: Tools selection/Tools option - merge two first pane into tab
Second tab: Original and Result
And
1. move filename into header of window
2. move buttons First,Prev,Next,Last towards left
3. Move Execute panel towards left

What do you think about it?

**Comment by TeaM-TL** [comment]
#81 move filename into header of window - done in 3.5.4
![2021-02-07_01-34-42_887907](https://user-images.githubusercontent.com/55061453/107133046-c2810680-68e4-11eb-8f8a-77ad76788339.png)

**Comment by gingerbeardman** [comment]
This is great progress towards the solution.

I think original/result image tab, or toggle?, is a good idea.

I have to think about what you mean with regards to first table tools selection/option.

**Comment by gingerbeardman** [comment]
eg. Scale/Resize

currently:

| FullHD | 2K | 4K |
|--------|----|----|
| Pixels | Percent | Apply |

suggestion:

| FullHD | Pixels |
|--------|----|
| 2K | Percent |
| 4K | Apply |

even though number of rows is now larger, the area used is a closer to a square.

**Comment by TeaM-TL** [comment]
merge tools selection and tool options
![obraz](https://user-images.githubusercontent.com/55061453/107158774-98831f00-698c-11eb-9d2f-27937f333694.png)
It shoul help a lot

**Comment by TeaM-TL** [comment]
IMHO before change order option eg. scale/resize, I have to add a scrolbar (#80 ), but slider will eat some pixels.
