### ISSUE TITLE
Allow 100% and 200% view sizes

### ISSUE THREAD

**Issue by gingerbeardman** [TeaM-TL/FotoKilof#83]
**Is your feature request related to a problem? Please describe.**

- I want to view original and preview images at 100% 1:1 size

**Describe the solution you'd like**

- Options for 100% (and 200%?) in zoom dropdown

**Describe alternatives you've considered**

n/a

**Comment by TeaM-TL** [comment]
1. workaround: for now use preview.
2. solution: it needs rework preview system, now is simple: show full picture i required size. I'm not sure that it is right way.
Fotokilof is not replacement for GIMP, it is only overlay for ImageMagick, for fast and mass operation on pictures
